name: Unit Test

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

permissions: {}

jobs:
  unit-test:
    uses: devjskit/github-workflows/.github/workflows/unit-test.yml@v1

  # coverage:
  #   uses: devjskit/github-workflows/.github/workflows/coverage.yml@v1
  #   needs: unit-test
  #   permissions:
  #     id-token: write
